export enum FirestoreCollections {
  TRANSLATIONS = "translations",
  USER_MESSAGES = "user_messages",
  TRANSLATION_VERSIONS = "translation_versions",
  USER_PROFILES = "user_profiles",
  SETTINGS = "user_settings",
  TRANSLATION_CREDITS = "translation_credits",
  SUBSCRIPTIONS = "subscriptions",
  REFRAMINGS = "reframings",
  USERS = "users",
  USER_REFRAMING_MESSAGES = "user_reframing_messages",
  CHECK_INS = "check_ins",
  CONVERSATIONS = "conversations",
  MESSAGES = "messages",
  USER_CONNECTIONS = "user_connections",
  CONVERSATION_USER_DETAILS = "conversation_user_details",
  USER_PRIVATE_CONVERSATION_DETAILS = "user_private_conversation_details",
  BLOCKED_USERS = "blocked_users",
}
