export const toxicPhrases: string[] = [
  // Clear direct insults
  "idiot",
  "moron",
  "stupid",
  "dumbass",
  "bitch",
  "asshole",
  "fucker",
  "prick",
  "loser",
  "retard",
  "psycho",
  "crazy",
  "whore",
  "slut",
  "fatass",
  "dick",
  "scumbag",

  // Emotionally attacking or shaming
  "worthless",
  "lazy",
  "youre just like your mother",
  "youre just like your father",
  "you only care about yourself",
  "i cant stand you",
  "you act like a child",
  "you never take responsibility",
  "you always play the victim",
  "youre the worst",
  "this relationship is a joke",
  "you always make it about you",
  "you twist everything i say",
  "youre so full of yourself",
  "youre crazy",
  "youre insane",
  "youre impossible",
  "youre so annoying",
  "youre pathetic",
  "youre selfish",
  "you never listen",
  "you always do this",
  "you ruin everything",
  "you dont care",
  "youre a liar",
  "youre the problem",
  "this is your fault",
  "you make me sick",
  "youre too much",
  "youre full of shit",
  "you dont love me",

  // Dismissive, minimizing, controlling
  "calm down",
  "grow up",
  "man up",
  "shut up",
  "get over it",
  "cry me a river",
  "here we go again",
  "youre too sensitive",
  "stop being dramatic",
  "youre overreacting",
  "boo hoo",
  "im leaving",
  "you need me",
  "i could do better",
  "youll never find better",
  "youre lucky im here",
  "i shouldve left",
  "you dont deserve me",
  "youre nothing without me",
  "i dont owe you",
  "dont push me",
  "you better stop",
  "ill walk away",
  "dont test me",
  "youll regret this",
];
