import { Emotion, Need } from "./types";

export const needsList: Need[] = [
  { key: "listening", label: "Listening", category: "relational" },
  { key: "reassurance", label: "Reassurance", category: "emotional" },
  { key: "connection", label: "Connection", category: "relational" },
  { key: "safety", label: "Safety", category: "emotional" },
  { key: "understanding", label: "Understanding", category: "relational" },
  { key: "acceptance", label: "Acceptance", category: "relational" },
  { key: "presence", label: "Presence", category: "communication" },
  { key: "apology", label: "Apology", category: "relational" },
  { key: "honesty", label: "Honesty", category: "communication" },
  { key: "space", label: "Space", category: "emotional" },
  { key: "time", label: "Time", category: "logistical" },
  { key: "directness", label: "Directness", category: "communication" },
  { key: "respect", label: "Respect", category: "relational" },
  { key: "change", label: "Change", category: "logistical" },
  { key: "fairness", label: "Fairness", category: "relational" },
  { key: "closure", label: "Closure", category: "logistical" },
  { key: "affection", label: "Affection", category: "relational" },
  { key: "relief", label: "Relief", category: "emotional" },
  { key: "trust", label: "Trust", category: "relational" },
  { key: "reliability", label: "Reliability", category: "logistical" },
  { key: "calm", label: "Calm", category: "emotional" },
];

export const emotionsList: Emotion[] = [
  { key: "hurt", label: "Hurt", category: "relational" },
  { key: "unheard", label: "Unheard", category: "relational" },
  { key: "unvalued", label: "Unvalued", category: "relational" },
  { key: "angry", label: "Angry", category: "emotional" },
  { key: "frustrated", label: "Frustrated", category: "emotional" },
  { key: "anxious", label: "Anxious", category: "emotional" },
  { key: "afraid", label: "Afraid", category: "emotional" },
  { key: "insecure", label: "Insecure", category: "emotional" },
  { key: "sad", label: "Sad", category: "emotional" },
  { key: "lonely", label: "Lonely", category: "relational" },
  { key: "hopeless", label: "Hopeless", category: "emotional" },
  { key: "grieving", label: "Grieving", category: "emotional" },
  { key: "confused", label: "Confused", category: "cognitive" },
  { key: "disappointed", label: "Disappointed", category: "emotional" },
  { key: "disrespected", label: "Disrespected", category: "relational" },
  { key: "trapped", label: "Trapped", category: "shutdown" },
  { key: "numb", label: "Numb", category: "shutdown" },
  { key: "curious", label: "Curious", category: "positive" },
  { key: "calm", label: "Calm", category: "positive" },
  { key: "hopeful", label: "Hopeful", category: "positive" },
  { key: "open", label: "Open", category: "positive" },
  { key: "loved", label: "Loved", category: "relational" },
  { key: "grateful", label: "Grateful", category: "positive" },
];
